from datetime import datetime, timezone
from pathlib import Path

from deplar.graph.store import DependencyGraph


class ClaudeMdGenerator:
    def __init__(self, graph: DependencyGraph, repo_name: str):
        self.graph = graph
        self.repo_name = repo_name

    def generate(self) -> str:
        deps = self.graph.get_dependencies(self.repo_name)
        dependents = self.graph.get_dependents(self.repo_name)
        blast = self.graph.blast_radius(self.repo_name)

        # split deps by type
        http_deps, kafka_emits, kafka_subs, other_deps = [], [], [], []

        for _, to, data in self.graph.g.edges(self.repo_name, data=True):
            types = data.get("dep_types", [])
            confidence = data.get("confidence", 0.0)
            conf_label = "high" if confidence >= 0.8 else \
                         "medium" if confidence >= 0.5 else "low"
            entry = f"- {to} [confidence: {conf_label}]"

            if "kafka" in types:
                kafka_emits.append(f"- {to} (Kafka topic) [confidence: {conf_label}]")
            elif "http" in types or "feign" in types or "grpc" in types:
                type_label = next(t for t in types
                                  if t in ("http", "feign", "grpc"))
                http_deps.append(f"- {to} ({type_label}) [confidence: {conf_label}]")
            else:
                other_deps.append(entry)

        lines = [
            f"# Dependency context for `{self.repo_name}`",
            f"> Auto-generated by deplar on "
            f"{datetime.now(timezone.utc).strftime('%Y-%m-%d')}. "
            f"Re-run `deplar claude-md .` to refresh.\n",
        ]

        # services this repo calls
        lines.append("## This service calls")
        if http_deps:
            lines.extend(http_deps)
        elif not other_deps:
            lines.append("- none detected")
        if other_deps:
            lines.extend(other_deps)

        # kafka topics emitted
        lines.append("\n## Events emitted")
        if kafka_emits:
            lines.extend(kafka_emits)
        else:
            lines.append("- none detected")

        # who calls this repo
        lines.append("\n## This service is called by")
        if dependents:
            for d in dependents:
                lines.append(f"- {d}")
        else:
            lines.append("- none detected (or not yet scanned)")

        # blast radius
        lines.append("\n## Blast radius")
        if blast:
            lines.append(
                "Changes here may affect the following services "
                "(directly or transitively):"
            )
            for s in sorted(blast):
                lines.append(f"- {s}")
        else:
            lines.append("- no downstream dependents detected")

        # instructions for the agent
        lines.append("\n## Agent instructions")
        lines.append(
            "Before modifying any API contract, public method signature, "
            "or Kafka topic in this service:"
        )
        lines.append(
            "1. Check **This service is called by** — "
            "those repos need coordinated updates"
        )
        lines.append(
            "2. Check **Blast radius** — "
            "transitive dependents may also be affected"
        )
        lines.append(
            "3. Run `deplar scan .` after making changes "
            "to keep this file current"
        )

        return "\n".join(lines)

    def write(self, output_path: Path = None):
        content = self.generate()
        path = output_path or Path("CLAUDE.md")
        path.write_text(content)
        return path